name: bitcoin_bech32_ng
version: 0.3.0
description: Library implementing Bitcoins BIP173 (Bech32 encoding) specification in a Flutter friendly fashion.
homepage: https://github.com/sigrlami/bitcoin_bech32

dependencies:
    convert: ^3.1.1

dev_dependencies:
    hex: ^0.2.0
    pedantic: ^1.11.0
    test: ^1.16.5

environment:
  sdk: ">=2.18.0 <3.0.0"
